# Generated by Django 5.2.11 on 2026-03-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, default='Sparkles', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('complexity_time', models.CharField(default='O(n)', max_length=50)),
                ('complexity_space', models.CharField(default='O(1)', max_length=50)),
                ('complexity_time_rating', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], default='average', max_length=10)),
                ('complexity_space_rating', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], default='good', max_length=10)),
                ('code_python', models.JSONField(blank=True, default=dict)),
                ('code_cpp', models.JSONField(blank=True, default=dict)),
                ('code_c', models.JSONField(blank=True, default=dict)),
                ('code_rust', models.JSONField(blank=True, default=dict)),
                ('explanation_problem', models.TextField(blank=True)),
                ('explanation_intuition', models.TextField(blank=True)),
                ('explanation_walkthrough', models.TextField(blank=True)),
                ('explanation_when_to_use', models.TextField(blank=True)),
                ('explanation_fun_fact', models.TextField(blank=True)),
                ('explanation_research_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(default='Box', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('data', models.TextField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='algorithms.algorithm')),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithms', to='algorithms.category'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('rust', 'Rust')], default='python', max_length=10)),
                ('explanation', models.TextField(blank=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='algorithms.algorithm')),
            ],
        ),
    ]
