# Generated by Django 5.2.11 on 2026-03-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icon', models.CharField(default='Box', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('complexity_time', models.CharField(default='O(n)', max_length=50)),
                ('complexity_space', models.CharField(default='O(1)', max_length=50)),
                ('complexity_time_rating', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], default='average', max_length=10)),
                ('complexity_space_rating', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], default='good', max_length=10)),
                ('code', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='algorithms.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
